### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by gdjssfxy302** [zake7749/Chatbot#42]
TypeError: cannot use a string pattern on a bytes-like object
请问题主大大，这个问题如何解决？运行demo_chatbot.py后，能够运行成功，但输入一句话“很高兴认识你”时，无法得到一个确确的回答。
回复出现如下信息：
Traceback (most recent call last):
  File "E:/python_work/pycharm/Chatbot-master/demo_chatbot.py", line 4, in <module>
    chatter.waiting_loop()
  File "E:\python_work\pycharm\Chatbot-master\Chatbot\chatbot.py", line 65, in waiting_loop
    res = self.listen(speech)
  File "E:\python_work\pycharm\Chatbot-master\Chatbot\chatbot.py", line 109, in listen
    response,stauts,target,candiates = self.getResponseOnRootDomains(target)
  File "E:\python_work\pycharm\Chatbot-master\Chatbot\chatbot.py", line 149, in getResponseOnRootDomains
    status,response = handler.get_response(self.speech, self.speech_domain, target)
  File "E:\python_work\pycharm\Chatbot-master\Chatbot\task_modules\other\stock.py", line 30, in get_response
    stock_no = self.get_stock_no(nm)
  File "E:\python_work\pycharm\Chatbot-master\Chatbot\task_modules\other\stock.py", line 69, in get_stock_no
    m = re.search('([0-9]{4}[ ]{2}|[0-9]{5}[ LRU]{1}|[0-9]6),([^ ]*)( *),',col)
  File "D:\python\python-3.5.4\lib\re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

Process finished with exit code 1

**Comment by zake7749** [comment]
這是因為您的輸入被歸類至功能性模組，如果您不需要使用到其他模組的功能，
可以將 https://github.com/zake7749/Chatbot/blob/master/Chatbot/chatbot.py#L106 的 threshold 設為 1，
不好意思，當時沒提供完整的參數介面。

此外，因為搜尋的語料是基於繁體中文，
我建議您將「很高兴认识你」轉成繁體中文再做輸入。

我目前正忙於其他工作，之後回覆若稍晚還請見諒。

**Comment by gdjssfxy302** [comment]
> 這是因為您的輸入被歸類至功能性模組，如果您不需要使用到其他模組的功能，
> 可以將 https://github.com/zake7749/Chatbot/blob/master/Chatbot/chatbot.py#L106 的 threshold 設為 1，
> 不好意思，當時沒提供完整的參數介面。
> 此外，因為搜尋的語料是基於繁體中文，
> 我建議您將「很高兴认识你」轉成繁體中文再做輸入。
> 我目前正忙於其他工作，之後回覆若稍晚還請見諒。

@zake7749 首先谢谢题注的解答了，我按照你所说的把threshold的参数改为1，就可以得到回复了，每一句话都可以得到一句回复。但是还有一个问题：发现输入所有的问题，回复的也就是那几句，“原来如此”，“我不太明白你的意思”，或者直接回复None，没有针对性，这个问题如何改进呢？
